#!/bin/sh
BUILD_DIR=$1
RELEASE_VERSION=$2
SUFFIX=$3
ARCH_SUFFIX=$4

mv $BUILD_DIR/install-root/ skyhub-$ARCH_SUFFIX-$RELEASE_VERSION.$BITBUCKET_BUILD_NUMBER
rm skyhub-$ARCH_SUFFIX-$RELEASE_VERSION.$BITBUCKET_BUILD_NUMBER/.version
tar -czvf skyhub-$ARCH_SUFFIX-$SUFFIX.tar.gz skyhub-$ARCH_SUFFIX-$RELEASE_VERSION.$BITBUCKET_BUILD_NUMBER

rm -rf skyhub-$ARCH_SUFFIX-$RELEASE_VERSION.$BITBUCKET_BUILD_NUMBER
